"""add missing FK indexes on field_corrections, usage_records, webhook_deliveries

Revision ID: 38b54ac5da5d
Revises: 76dc03c01c9a
Create Date: 2026-08-17 14:17:48.294914
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "38b54ac5da5d"
down_revision: str | None = "76dc03c01c9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_field_corrections_document_id"), "field_corrections", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_records_document_id"), "usage_records", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_records_extraction_id"), "usage_records", ["extraction_id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_organization_id"),
        "webhook_deliveries",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_deliveries_organization_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_usage_records_extraction_id"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_document_id"), table_name="usage_records")
    op.drop_index(op.f("ix_field_corrections_document_id"), table_name="field_corrections")
    # ### end Alembic commands ###
